
<digit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
<digits> ::= <digit>
            | <digits> <digit>
<character> ::= "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" | "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P"  | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"
<characters> ::= <character>
            | <characters> <character>

<digit-or-character> ::= <digit>
            | <character>
<digits-and-characters> ::= <digit-or-character> | <digits-and-characters> <digit-or-character>

<symbol> ::= "|" | " " | "!" | "#" | "$" | "%" | "&" | "(" | ")" | "*" | "+" | "," | "-" | "." | "/" | ":" | ";" | ">" | "=" | "<" | "?" | "@" | "[" | "\\" | "]" | "^" | "_" | "'" | "\'" | "{" | "}" | "~" | "\n" | "\r" | "\t" | "\""
<symbols> ::= <symbol>
            | <symbols> <symbol>
<text> ::= <digit>
            | <character>
            | <symbol>
<all-text-symbols> ::= <text> | <all-text-symbols> <text>

<identifier-and-function-call> ::= <identifier>
			| <identifier> "(" ")"
			| <identifier> "(" <call-arguments> ")"

<constant> ::= <digits>
            | <digits> "." <digits>
            | <digits> "."
            | "." <digits>
			| <identifier-and-function-call>

<string> ::= "'" <all-text-symbols> "'"
            | "\"" <all-text-symbols> "\""

<factor> ::= "(" <unary-expression> ")""
            | <constant>

<term> ::= <term> "*" <factor>
            | <term> "/" <factor>
            | <factor>

<math> ::= <math> "+" <term>
            | <math> "-" <term>
            | <term>

<relational-exp> ::= <math> <relational-symbol> <math>
            | <math>

<expression> ::= <relational-exp>
            | <relational-exp> <logical-symbol> <unary-expression>

<unary-expression> ::= <expression>
            | <unary-symbol> <unary-expression>

<unary-symbol> ::= "-"
			| "!"
			
<logical-symbol> ::= "&&"
            | "||"

<relational-symbol> ::= "=="
            | ">="
            | "<="
            | "!="
            | ">"
            | "<"

<type> ::= "int"
            | "string"
            | "float"
<identifier> ::= <digits-and-characters>

	
			
<declaration-statement> ::=	 | <type> <identifier> ";"
			| <type> <identifier> "=" <unary-expression> ";"
			| <type> <identifier> "=" <string> ";"
		
		
		
<call-arguments> ::= <unary-expression>
            | <unary-expression> "," <unary-expression>	
<call-and-assignment-statement> ::= <identifier> "(" <call-arguments> ")" ";"
			| <identifier> "(" ")" ";"
			| <identifier> "=" <unary-expression> ";"
			| <identifier> "=" <string> ";"
			
			

<jump-statement> ::= "nutraukti" ";"
            | "testi" ";"
			| "grazinti" ";"
			| "grazinti" <unary-expression> ";"
			
				

<statement-region> ::= ":" "(" <statements> ")"
					 | ":" "(" ")"
<pakolei-statement> ::= "pakolei" "(" <unary-expression> ")" <statement-region>
<kitaip-statement> ::= "kitaip" <statement-region>
<kitaip-jei-statement> ::= "kitaip-jei" "(" <unary-expression> ")" <statement-region>
            | "kitaip-jei" "(" <unary-expression> ")" <statement-region> <kitaip-jei-statement>
            | "kitaip-jei" "(" <unary-expression> ")" <statement-region> <kitaip-statement>
<jei-statement> ::= "jei" "(" <unary-expression> ")" <statement-region>
            | "jei" "(" <unary-expression> ")" <statement-region> <kitaip-jei-statement>
            | "jei" "(" <unary-expression> ")" <statement-region> <kitaip-statement>

<statement> ::= <jei-statement>
            | <pakolei-statement>
			| <jump-statement>
			| <call-and-assignment-statement>
			| <declaration-statement>
<statements> ::= <statement>
            | <statements> <statement>
			
			
			
<declaration-argument> ::= <unary-expression>
			| <type> <identifier>
			| <identifier>
<declaration-arguments> ::= <declaration-argument>
            | <arguments> "," <declaration-argument>
<function-statement> ::= <type> <identifier> "(" <declaration-arguments> ")" <statement-region>
			| <type> <identifier> "(" ")" <statement-region>
<functions> ::= <function-statement>
			| <functions> <function-statement>
			
			
			
			
<start> ::= <functions> EOF
